[package]
name = "gbmu"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
pixels = "0.15.0"
winit = "0.30.11"
eframe = "0.25"
tokio = { version = "1.46.1", features = ["full"] }
egui_extras = "0.33.0"
flamegraph = "0.6.11"
